controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


index:
    path: /
    controller: App\Controller\HomeController::index

portfolio:
    path: /portfolio
    controller: App\Controller\PortfolioController::portfolio

contact:
    path: /contact
    controller: App\Controller\ContactController::contact

contact_success:
    path: /contact/success
    controller: App\Controller\ContactController::success
